server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YasinduWishmith/spring-cloud-cofig-store
          search-paths:
           - '*service'



