#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/YasinduWishmith/spring-cloud-cofig-store
#          search-paths:
#           - '*service'
spring:
  datasource:
    uri: jdbc:mysql://localhost:3306/rentcarsDB?createDatabaseIfNotExist=true
    username: root
    password: yasindu
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



