#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/YasinduWishmith/spring-cloud-cofig-store
#          search-paths:
#           - '*service'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentcarsDB?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
security:
  oauth2:
    resource:
      token-info-uri: http//localhost:9292/auth/check_token
    client:
      client-id: web
      client-secret: pin



